// APEX.BUILD Terminal Themes
// Custom terminal color schemes matching IDE themes

import { TerminalTheme } from './types';

export const terminalThemes: Record<string, TerminalTheme> = {
  cyberpunk: {
    name: 'Neon Cyberpunk',
    foreground: '#00f5ff',
    background: '#0a0a0a',
    cursor: '#00f5ff',
    cursorAccent: '#0a0a0a',
    selection: 'rgba(0, 245, 255, 0.3)',
    black: '#1a1a2e',
    red: '#ff4444',
    green: '#39ff14',
    yellow: '#ffaa00',
    blue: '#00f5ff',
    magenta: '#ff0080',
    cyan: '#00d4ff',
    white: '#e0e0e0',
    brightBlack: '#4a4a5e',
    brightRed: '#ff6b6b',
    brightGreen: '#5dff47',
    brightYellow: '#ffcc00',
    brightBlue: '#5cf5ff',
    brightMagenta: '#ff4da6',
    brightCyan: '#5de8ff',
    brightWhite: '#ffffff',
  },

  matrix: {
    name: 'Matrix Digital',
    foreground: '#00ff41',
    background: '#000000',
    cursor: '#00ff41',
    cursorAccent: '#000000',
    selection: 'rgba(0, 255, 65, 0.3)',
    black: '#001100',
    red: '#ff0000',
    green: '#00ff41',
    yellow: '#ffa500',
    blue: '#00ffff',
    magenta: '#ff00ff',
    cyan: '#00ffff',
    white: '#90ee90',
    brightBlack: '#003300',
    brightRed: '#ff4444',
    brightGreen: '#39ff73',
    brightYellow: '#ffcc00',
    brightBlue: '#5cffff',
    brightMagenta: '#ff5cff',
    brightCyan: '#5cffff',
    brightWhite: '#c0ffc0',
  },

  synthwave: {
    name: 'Synthwave Retro',
    foreground: '#ffffff',
    background: '#0f0f23',
    cursor: '#ff006e',
    cursorAccent: '#0f0f23',
    selection: 'rgba(255, 0, 110, 0.3)',
    black: '#1a1a2e',
    red: '#ff073a',
    green: '#06ffa5',
    yellow: '#ffbe0b',
    blue: '#4361ee',
    magenta: '#8338ec',
    cyan: '#ff006e',
    white: '#dda0dd',
    brightBlack: '#3a3a5e',
    brightRed: '#ff4d6a',
    brightGreen: '#47ffb8',
    brightYellow: '#ffd747',
    brightBlue: '#6e8aff',
    brightMagenta: '#a366f5',
    brightCyan: '#ff4d91',
    brightWhite: '#ffffff',
  },

  neonCity: {
    name: 'Neon City',
    foreground: '#ffffff',
    background: '#0d1421',
    cursor: '#00d4ff',
    cursorAccent: '#0d1421',
    selection: 'rgba(0, 212, 255, 0.3)',
    black: '#1e2a3a',
    red: '#ff4757',
    green: '#2ed573',
    yellow: '#ffa502',
    blue: '#3742fa',
    magenta: '#ff0080',
    cyan: '#00d4ff',
    white: '#b0c4de',
    brightBlack: '#3e4a5a',
    brightRed: '#ff6b7a',
    brightGreen: '#5de896',
    brightYellow: '#ffc04d',
    brightBlue: '#5c64ff',
    brightMagenta: '#ff4da6',
    brightCyan: '#4de4ff',
    brightWhite: '#ffffff',
  },

  dracula: {
    name: 'Dracula',
    foreground: '#f8f8f2',
    background: '#282a36',
    cursor: '#f8f8f2',
    cursorAccent: '#282a36',
    selection: 'rgba(68, 71, 90, 0.5)',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  },

  monokai: {
    name: 'Monokai',
    foreground: '#f8f8f2',
    background: '#272822',
    cursor: '#f8f8f2',
    cursorAccent: '#272822',
    selection: 'rgba(73, 72, 62, 0.5)',
    black: '#272822',
    red: '#f92672',
    green: '#a6e22e',
    yellow: '#e6db74',
    blue: '#66d9ef',
    magenta: '#ae81ff',
    cyan: '#a1efe4',
    white: '#f8f8f2',
    brightBlack: '#49483e',
    brightRed: '#fc618d',
    brightGreen: '#bde64c',
    brightYellow: '#f9f098',
    brightBlue: '#84e1ff',
    brightMagenta: '#c49bff',
    brightCyan: '#bfffea',
    brightWhite: '#ffffff',
  },

  nord: {
    name: 'Nord',
    foreground: '#d8dee9',
    background: '#2e3440',
    cursor: '#d8dee9',
    cursorAccent: '#2e3440',
    selection: 'rgba(67, 76, 94, 0.5)',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#d08770',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
  },

  gruvbox: {
    name: 'Gruvbox Dark',
    foreground: '#ebdbb2',
    background: '#282828',
    cursor: '#ebdbb2',
    cursorAccent: '#282828',
    selection: 'rgba(146, 131, 116, 0.3)',
    black: '#282828',
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    white: '#a89984',
    brightBlack: '#928374',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightMagenta: '#d3869b',
    brightCyan: '#8ec07c',
    brightWhite: '#ebdbb2',
  },

  tokyo: {
    name: 'Tokyo Night',
    foreground: '#a9b1d6',
    background: '#1a1b26',
    cursor: '#c0caf5',
    cursorAccent: '#1a1b26',
    selection: 'rgba(40, 52, 74, 0.8)',
    black: '#15161e',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#a9b1d6',
    brightBlack: '#414868',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
  },
};

export const getTerminalTheme = (themeId: string): TerminalTheme => {
  return terminalThemes[themeId] || terminalThemes.cyberpunk;
};

export const getXtermTheme = (themeId: string) => {
  const theme = getTerminalTheme(themeId);
  return {
    foreground: theme.foreground,
    background: theme.background,
    cursor: theme.cursor,
    cursorAccent: theme.cursorAccent,
    selectionBackground: theme.selection,
    selectionForeground: theme.foreground,
    selectionInactiveBackground: theme.selection,
    black: theme.black,
    red: theme.red,
    green: theme.green,
    yellow: theme.yellow,
    blue: theme.blue,
    magenta: theme.magenta,
    cyan: theme.cyan,
    white: theme.white,
    brightBlack: theme.brightBlack,
    brightRed: theme.brightRed,
    brightGreen: theme.brightGreen,
    brightYellow: theme.brightYellow,
    brightBlue: theme.brightBlue,
    brightMagenta: theme.brightMagenta,
    brightCyan: theme.brightCyan,
    brightWhite: theme.brightWhite,
  };
};

export default terminalThemes;
